# .github/actions/ssh-deploy.yml

name: SSH Deploy Action

runs:
  using: 'composite'
  steps:
    - name: SSH deploy step 1
      run: |
        ssh -i /home/sandeep/goac-sandeep/goac-sandeep.pem ubuntu@ec2-13-232-52-59.ap-south-1.compute.amazonaws.com 'echo "Deleting existing files in remote directory..." && sudo rm -rf /var/www/html/*'
        ssh -i /home/sandeep/goac-sandeep/goac-sandeep.pem ubuntu@ec2-13-232-52-59.ap-south-1.compute.amazonaws.com 'echo "Deploying files to server..."'
        rsync -avz --delete /home/sandeep/sandeep11/sandeep/my-app/* -e "ssh -i /home/sandeep/goac-sandeep/goac-sandeep.pem" ubuntu@ec2-13-232-52-59.ap-south-1.compute.amazonaws.com:/var/www/html/

    - name: SSH deploy step 2
      run: |
        ssh -i /home/sandeep/goac-sandeep/goac-sandeep.pem ubuntu@ec2-13-232-52-59.ap-south-1.compute.amazonaws.com 'echo "Deployment completed."'
 
