name: SSH Deploy Action

inputs:
  ssh-private-key:
    description: '/home/sandeep/goac-sandeep/goac-sandeep.pem'
    required: true
  server-address:
    description: 'ec2-35-154-112-71.ap-south-1.compute.amazonaws.com'
    required: true
  remote-directory:
    description: '/var/www/html'
    required: true
  local-directory:
    description: '~/sandeep11/sandeep/my-app/build'
    required: true

runs:
  using: 'composite'
  steps:
    - name: SSH deploy step 1
      run: |
        ssh -i ${{ inputs.ssh-private-key }} ${{ inputs.server-address }} 'echo "Deleting existing files in remote directory..." && sudo rm -rf ${{ inputs.remote-directory }}/*'
        ssh -i ${{ inputs.ssh-private-key }} ${{ inputs.server-address }} 'echo "Deploying files to server..."'
        rsync -avz --delete ${{ inputs.local-directory }}/* -e "ssh -i ${{ inputs.ssh-private-key }}" ${{ inputs.server-address }}:${{ inputs.remote-directory }}
      shell: bash
    - name: SSH deploy step 2
      run: |
        ssh -i ${{ inputs.ssh-private-key }} ${{ inputs.server-address }} 'echo "Deployment completed."'
      shell: bash

