# .github/workflows/deploy.yml

name: SSH Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH Deploy Action
        uses: ./.github/actions/ssh-deploy.yml
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
          remote-host: ${{ secrets.HOST_DNS }}

      - name: Run the program
        run: npm start

