# .github/workflows/deploy.yml

name: SSH Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH Deploy Action
        uses: ./home/sandeep/sandeep11/sandeep/.github/actions/ssh-deploy.yml


      - name: Run the program
        run: npm start

