# .github/workflows/deploy.yml

name: SSH Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH Deploy Action
        uses: ./.github/actions/react
        
      - name: Run the program
        run: npm start

